// generated by java2js on 2016-01-26T14:25:10.971

// generated from org.agilemicroservices.java2js.mock2.MockOwner
Ext.define('Example.MockOwner', {
    extend: 'Ext.data.Model',
    fields: [
        { name: 'fullName', type: 'string' },
        { name: 'id', type: 'int' },
        { name: 'phoneNumbers', type: 'auto' },
    ],
});

// generated from org.agilemicroservices.java2js.mock.MockBase
Ext.define('Example.MockBase', {
    extend: 'Ext.data.Model',
    fields: [
        { name: 'baseId', type: 'int' },
    ],
});

// generated from org.agilemicroservices.java2js.mock.MockAccount
Ext.define('Example.MockAccount', {
    extend: 'Example.MockBase',
    fields: [
        { name: 'accountId', type: 'int' },
        { name: 'accountNumber', type: 'string' },
        { name: 'owner', type: 'Example.MockOwner' },
        { name: 'restricted', type: 'bool' },
        { name: 'secondaryOwners', type: 'auto' },
    ],
});

